version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    build: .
    volumes:
      - .:/code
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py migrate --run-syncdb  &&
      python manage.py initadmin &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  redis:
    image: redis:alpine
    command: redis-server
  celery:
    restart: always
    build:
      context: .
    command: celery  -A alpha_vantage worker --loglevel=INFO --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo
    volumes:
      - ./data/celery:/celery
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - api
  celery-beat:
    build: .
    command: celery -A alpha_vantage.celery beat -l info
    volumes:
      - ./data/celery:/celery
    depends_on:
      - redis